#!/usr/bin/env python3
"""
Extract the set of courses offered each term from Coe's published schedules.

Usage:
    python3 tools/extract_offerings.py [--fall PATH] [--spring PATH] [--out PATH]

Produces data/offerings_2026.json mapping term → course codes for the
2026-2027 academic year, so the Suggested Plan can annotate course-picker
dropdowns with "offered [F]", "[S]", or "[FS]" badges.

Only extracts the course code set per term, not meeting times / sections.
Rerun when the Registrar publishes updated schedules.
"""

from __future__ import annotations
import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# Schedule row starts at column 0 with "PREFIX NNN SS ..." — prefix is 2-4
# uppercase letters, NNN is the course number (optionally suffixed with L/C/
# or a letter for variants like "100X"), SS is the 2-digit section number.
COURSE_RE = re.compile(r"^([A-Z]{2,4})\s+(\d{3}[A-Z]?)\s+\d{2}\b")

# Lines that are clearly page headers / legends and never course rows.
SKIP_PREFIXES = ("W-Writing Emphasis", "Course Schedules", "Course Number/Title")


def run_pdftotext(pdf_path: Path) -> str:
    result = subprocess.run(
        ["pdftotext", "-layout", str(pdf_path), "-"],
        check=True, capture_output=True, text=True,
    )
    return result.stdout


def parse_courses(text: str) -> set[str]:
    """Return the set of PREFIX-NUM course codes appearing in a schedule PDF."""
    codes: set[str] = set()
    for raw in text.splitlines():
        line = raw.rstrip()
        if not line or line.lstrip().startswith(SKIP_PREFIXES):
            continue
        if not line or line[0].isspace():
            # Continuation rows (second meeting pattern) are indented — skip.
            continue
        m = COURSE_RE.match(line)
        if m:
            codes.add(f"{m.group(1)}-{m.group(2)}")
    return codes


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--fall",
                    default=str(REPO / "catalogs" / "FA 26 3.31.26.pdf"))
    ap.add_argument("--spring",
                    default=str(REPO / "catalogs" / "SP 2026 11.12.2025.pdf"))
    ap.add_argument("--out",
                    default=str(REPO / "data" / "offerings_2026.json"))
    args = ap.parse_args()

    fall_pdf   = Path(args.fall)
    spring_pdf = Path(args.spring)
    out_path   = Path(args.out)

    fall_codes   = parse_courses(run_pdftotext(fall_pdf))   if fall_pdf.exists()   else set()
    spring_codes = parse_courses(run_pdftotext(spring_pdf)) if spring_pdf.exists() else set()

    output = {
        "version": "2026-2027",
        "notes": (
            "Generated by tools/extract_offerings.py. One entry per term; "
            "value is the sorted list of unique course codes offered that term "
            "(sections collapsed). Rerun when the Registrar publishes updates."
        ),
        "terms": {
            "fall": {
                "source": fall_pdf.name,
                "courses": sorted(fall_codes),
            },
            "spring": {
                "source": spring_pdf.name,
                "courses": sorted(spring_codes),
            },
        },
    }

    out_path.write_text(json.dumps(output, indent=2) + "\n")
    print(f"Wrote {out_path.relative_to(REPO)}")
    print(f"  Fall   {fall_pdf.name:40s}  {len(fall_codes):4d} courses")
    print(f"  Spring {spring_pdf.name:40s}  {len(spring_codes):4d} courses")
    both = fall_codes & spring_codes
    print(f"  Overlap (offered both terms): {len(both)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
